spring:
    servlet:
        multipart:
            enabled: true          #默认支持文件上传
            max-file-size: 200MB    # 最大支持文件大小
            max-request-size: 200MB # 最大支持请求大小
    datasource:
        username: sa
        password: 
        url: jdbc:h2:file:~/onedrive/ether/ether;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE  #FILE_LOCK=NO
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
logging:
    # level:
    #     root: info
    charset: 
        console: UTF-8
        file: UTF-8
        
file:
    data-dir: c:/environment/nginx-1.19.0/html/ether

docker:
    host: 192.168.241.128
    port: 2379
    registry: 
        api: hub.centit.com
        username: operator
        password: 0pC3ntit.!

harbor:
    api: hub.centit.com
    username: operator
    password: 0pC3ntit.!s
    
hazelcast:
    # instance-name: hazelcast-instance
    config:
        group:
            name: ether
            password: ether
        network:
            port: 5701
            join: true
            multicast:
                enabled: true
        map:
            default:
                time-to-live-sceconds: 86400
                max-idle-seconds: 300