spring:
    servlet:
        multipart:
            enabled: true          #默认支持文件上传
            max-file-size: 200MB    # 最大支持文件大小
            max-request-size: 200MB # 最大支持请求大小
    datasource:
        username: root
        password: Mysql1dF0r
        url: jdbc:mysql://sh-cdb-6z8s2pbe.sql.tencentcdb.com:21016/ether
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 15
            connection-timeout: 30000
            idle-timeout: 60000
    jpa:
        database-platform: org.hibernate.dialect.MySQL57Dialect
logging:
    # level:
    #     root: info
    charset: 
        console: UTF-8
        file: UTF-8
        
file:
    data-dir: c:/environment/nginx-1.19.0/html/ether

docker:
    host: 192.168.241.128
    port: 2379
    registry: 
        api: hub.centit.com
        username: operator
        password: 0pC3ntit.!

harbor:
    api: hub.centit.com
    username: operator
    password: 0pC3ntit.!s
    
hazelcast:
    # instance-name: hazelcast-instance
    config:
        group:
            name: ether
            password: ether
        network:
            port: 5701
            join: true
            multicast:
                enabled: true
        map:
            default:
                time-to-live-sceconds: 86400
                max-idle-seconds: 300